//
//  main.m
//  FlashCard
//
//  Created by Tzu-Chien Chiu on 9/2/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import <UIKit/UIKit.h>

#import "FCAppDelegate.h"

int main(int argc, char *argv[])
{
    /*
     Code generated by Xcode
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([FCAppDelegate class]));
    }
     */
    
    // When the app crash, check the description of 'exception' object to 
    // find out the reason.
    @autoreleasepool {
        @try {
            return UIApplicationMain(argc, argv, nil, NSStringFromClass([FCAppDelegate class]));
        }
        @catch (NSException *exception) {
            NSLog(@"%@",[exception callStackSymbols]);
            return 1;
        }
    }
}
